use std::io::Write;
use std::path::{Path, PathBuf};
use std::sync::{Arc, OnceLock};

use anyhow::Result;
use tokio::process::Command;

#[derive(Debug, Clone)]
pub struct BuildOutput {
    pub store_path: PathBuf,
}

static CURRENT_SYSTEM: OnceLock<String> = OnceLock::new();
/// Detect and cache the Nix system triple (e.g. `x86_64-linux`).
/// Called once at startup; must complete before any build/deploy.
pub async fn init_current_system() -> Result<()> {
    let output = Command::new("nix")
        .args([
            "eval",
            "--impure",
            "--raw",
            "--expr",
            "builtins.currentSystem",
        ])
        .output()
        .await?;

    if !output.status.success() {
        anyhow::bail!(
            "failed to detect Nix system: {}",
            String::from_utf8_lossy(&output.stderr).trim()
        );
    }

    let stdout = String::from_utf8(output.stdout)
        .map_err(|e| anyhow::anyhow!("nix eval output is not valid UTF-8: {e}"))?;
    let sys = stdout.trim().to_string();
    if sys.is_empty() {
        anyhow::bail!("nix eval builtins.currentSystem returned empty output");
    }
    // Reject values that don't look like a Nix system triple (e.g. x86_64-linux).
    if !sys
        .chars()
        .all(|c| c.is_ascii_alphanumeric() || c == '_' || c == '-')
        || !sys.contains('-')
    {
        anyhow::bail!(
            "nix eval returned unrecognized system triple format: {sys:?} \
             (expected e.g. x86_64-linux or aarch64-darwin)"
        );
    }
    let _ = CURRENT_SYSTEM.set(sys);
    Ok(())
}

/// Return the cached system triple; panics if `init_current_system` was not called.
#[inline]
pub fn current_system() -> &'static str {
    CURRENT_SYSTEM
        .get()
        .unwrap_or_else(|| {
            panic!(
                "current_system() called before init_current_system() — \
                 call init_current_system() at startup"
            )
        })
        .as_str()
}

/// Pluggable build backend — mirrors the `Ingress` trait pattern.
///
/// DeployPipeline holds an `Arc<dyn BuildBackend>` so future providers
/// (container-first, remote build farm, Bazel) can be swapped in without
/// touching the deploy orchestration.
#[async_trait::async_trait]
pub trait BuildBackend: Send + Sync {
    async fn build(&self, repo_path: &Path) -> Result<BuildOutput>;
}

/// Default build backend backed by `nix build` on the local machine.
#[derive(Debug, Default)]
pub struct NixBuilder;

/// Opt-in restricted Nix build mode (`RUSSEL_NIX_RESTRICTED=1` / `true` / `yes`).
///
/// When enabled, deploy builds:
/// - refuse auto-generated / non-regular `flake.nix` (require a committed flake)
/// - force `sandbox = true` and `sandbox-fallback = false` on `nix build`
///
/// See `docs/security/nix-builds.md` for the full threat model. This is a light
/// gate — not multi-tenant isolation. Host `nix.conf` (`trusted-users`,
/// builders, substituters) still applies; trusted users can override sandbox.
fn nix_restricted_enabled() -> bool {
    match std::env::var("RUSSEL_NIX_RESTRICTED") {
        Ok(v) => {
            let t = v.trim();
            t == "1" || t.eq_ignore_ascii_case("true") || t.eq_ignore_ascii_case("yes")
        }
        Err(_) => false,
    }
}

/// Extra `nix build` arguments when restricted mode is on.
fn restricted_nix_build_args() -> &'static [&'static str] {
    // Keep as flat argv so we can `.args(...)` without owning Strings.
    &[
        "--option",
        "sandbox",
        "true",
        "--option",
        "sandbox-fallback",
        "false",
    ]
}

impl NixBuilder {
    /// Marker inserted as the first line of auto-generated flake.nix files.
    /// Used to identify and optionally clean up generated flakes after a
    /// successful build, leaving the checkout clean.
    const GENERATED_MARKER: &'static str = "# Auto-generated by Russel — do not edit manually.\n";

    pub async fn ensure_flake_exists(&self, repo_path: &Path) -> Result<bool> {
        let flake_path = repo_path.join("flake.nix");

        // Restricted mode never auto-generates flakes (moving nixos-unstable pin,
        // unrestricted builder network). Require a committed regular flake.nix —
        // reject missing, symlink/non-file, and leftover auto-generated markers.
        if nix_restricted_enabled() {
            return self.validate_restricted_flake(&flake_path);
        }

        // Use create_new for atomic check-and-create (fail if exists, no TOCTOU).
        let mut opts = std::fs::OpenOptions::new();
        opts.write(true).create_new(true);
        #[cfg(unix)]
        {
            use std::os::unix::fs::OpenOptionsExt;
            opts.custom_flags(libc::O_NOFOLLOW | libc::O_CLOEXEC);
        }
        let mut file = match opts.open(&flake_path) {
            Ok(f) => f,
            Err(e) if e.kind() == std::io::ErrorKind::AlreadyExists => return Ok(false),
            Err(e) => return Err(e.into()),
        };

        let system = current_system();
        tracing::info!(system = %system, "No flake.nix found. Auto-detecting project type to generate a default flake.");

        let flake_body = if repo_path.join("Cargo.toml").exists() {
            tracing::info!("Detected Rust project.");
            format!(
                r#"{{
  description = "Auto-generated Rust flake by Russel";
  inputs.nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
  outputs = {{ self, nixpkgs }}:
    let
      pkgs = nixpkgs.legacyPackages.{system};
    in {{
      packages.{system}.default = pkgs.rustPlatform.buildRustPackage {{
        pname = "app";
        version = "0.1.0";
        src = ./.;
        cargoLock = {{
          lockFile = ./Cargo.lock;
        }};
      }};
    }};
}}"#,
                system = system
            )
        } else if repo_path.join("go.mod").exists() {
            tracing::info!("Detected Go project.");
            format!(
                r#"{{
  description = "Auto-generated Go flake by Russel";
  inputs.nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
  outputs = {{ self, nixpkgs }}:
    let
      pkgs = nixpkgs.legacyPackages.{system};
    in {{
      packages.{system}.default = pkgs.buildGoModule {{
        pname = "app";
        version = "0.1.0";
        src = ./.;
        vendorHash = null;
      }};
    }};
}}"#,
                system = system
            )
        } else {
            tracing::info!("Defaulting to static web server flake.");
            format!(
                r#"{{
  description = "Auto-generated Static site flake by Russel";
  inputs.nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
  outputs = {{ self, nixpkgs }}:
    let
      pkgs = nixpkgs.legacyPackages.{system};
    in {{
      packages.{system}.default = pkgs.writeShellScriptBin "app" ''
        cd ${{./.}}
        exec ${{pkgs.python3}}/bin/python3 -m http.server "$PORT"
      '';
    }};
}}"#,
                system = system
            )
        };

        let flake_content = format!("{}{}", Self::GENERATED_MARKER, flake_body);
        file.write_all(flake_content.as_bytes())?;
        tracing::info!("Successfully generated default flake.nix");
        Ok(true)
    }

    /// Restricted-mode gate: `flake.nix` must exist as a regular file and must
    /// not be a Russel auto-generated leftover (`GENERATED_MARKER`).
    fn validate_restricted_flake(&self, flake_path: &Path) -> Result<bool> {
        match std::fs::symlink_metadata(flake_path) {
            Ok(meta) => {
                if meta.file_type().is_symlink() || !meta.file_type().is_file() {
                    anyhow::bail!(
                        "RUSSEL_NIX_RESTRICTED=1 requires flake.nix to be a regular file \
                         (not a symlink or directory). See docs/security/nix-builds.md"
                    );
                }
                let content = std::fs::read_to_string(flake_path).map_err(|e| {
                    anyhow::anyhow!("RUSSEL_NIX_RESTRICTED=1: failed to read flake.nix: {e}")
                })?;
                if content.starts_with(Self::GENERATED_MARKER) {
                    anyhow::bail!(
                        "RUSSEL_NIX_RESTRICTED=1 refuses auto-generated flake.nix \
                         (remove it and commit a pinned flake). \
                         See docs/security/nix-builds.md"
                    );
                }
                Ok(false)
            }
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => {
                anyhow::bail!(
                    "RUSSEL_NIX_RESTRICTED=1 requires a committed flake.nix \
                     (auto-generation is disabled for supply-chain hygiene). \
                     See docs/security/nix-builds.md"
                );
            }
            Err(e) => Err(e.into()),
        }
    }

    /// Build using `nix build`; the inherent entry point for callers that
    /// hold a concrete `NixBuilder` (delegates to `build_package`).
    #[allow(dead_code)]
    pub async fn build(&self, repo_path: &Path) -> Result<BuildOutput> {
        self.build_package(repo_path).await
    }

    /// Shared implementation: generates a flake if missing, runs `nix build`,
    /// and cleans up the auto-generated flake on success.
    async fn build_package(&self, repo_path: &Path) -> Result<BuildOutput> {
        let generated = self.ensure_flake_exists(repo_path).await?;

        let build_result = self.build_inner(repo_path).await;

        // On success, remove the auto-generated flake to leave the checkout clean.
        // Only remove it if the marker is present (defense in depth: never delete
        // a flake.nix the user wrote themselves).
        if build_result.is_ok() && generated {
            let flake_path = repo_path.join("flake.nix");
            if let Ok(content) = std::fs::read_to_string(&flake_path)
                && content.starts_with(Self::GENERATED_MARKER)
            {
                if let Err(e) = std::fs::remove_file(&flake_path) {
                    tracing::warn!(
                        path = %flake_path.display(),
                        error = %e,
                        "failed to remove auto-generated flake.nix after successful build"
                    );
                } else {
                    tracing::info!("removed auto-generated flake.nix after successful build");
                }
            }
        } else if build_result.is_err() && generated {
            let flake_path = repo_path.join("flake.nix");
            tracing::warn!(
                path = %flake_path.display(),
                "build failed; leaving auto-generated flake.nix for inspection"
            );
        }

        build_result
    }

    async fn build_inner(&self, repo_path: &Path) -> Result<BuildOutput> {
        let system = current_system();
        let flake_ref = format!("path:{}#packages.{}.default", repo_path.display(), system);
        let restricted = nix_restricted_enabled();
        if restricted {
            tracing::info!(
                "RUSSEL_NIX_RESTRICTED enabled — forcing sandbox=true, sandbox-fallback=false"
            );
        }

        let mut cmd = Command::new("nix");
        cmd.arg("build")
            .arg(&flake_ref)
            .arg("--no-link")
            .arg("--print-out-paths");
        if restricted {
            cmd.args(restricted_nix_build_args().iter().copied());
        }
        let mut output = cmd.stderr(std::process::Stdio::inherit()).output().await?;

        if !output.status.success() {
            let fallback_ref = format!("path:{}#defaultPackage.{}", repo_path.display(), system);
            tracing::info!(system = %system, "packages.{}.default failed, trying defaultPackage", system);
            let mut fallback = Command::new("nix");
            fallback
                .arg("build")
                .arg(&fallback_ref)
                .arg("--no-link")
                .arg("--print-out-paths");
            if restricted {
                fallback.args(restricted_nix_build_args().iter().copied());
            }
            output = fallback
                .stderr(std::process::Stdio::piped())
                .output()
                .await?;

            if !output.status.success() {
                anyhow::bail!(
                    "nix build failed for both {} and {}:\n{}",
                    flake_ref,
                    fallback_ref,
                    String::from_utf8_lossy(&output.stderr).trim()
                );
            }
        }

        let store_path_raw = String::from_utf8_lossy(&output.stdout)
            .lines()
            .next()
            .unwrap_or_default()
            .trim()
            .to_string();

        if store_path_raw.is_empty() {
            anyhow::bail!("nix build produced an empty store path");
        }
        if !store_path_raw.starts_with("/nix/store/") {
            anyhow::bail!(
                "nix build returned unexpected path '{}' (expected /nix/store/ prefix)",
                store_path_raw
            );
        }
        let store_path: PathBuf = store_path_raw.into();

        Ok(BuildOutput { store_path })
    }
}

#[async_trait::async_trait]
impl BuildBackend for NixBuilder {
    async fn build(&self, repo_path: &Path) -> Result<BuildOutput> {
        self.build_package(repo_path).await
    }
}

/// Return the default build backend (local `nix build`).
pub fn default_builder() -> Arc<dyn BuildBackend> {
    Arc::new(NixBuilder)
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used)]
mod tests {
    use super::*;

    struct StubBuilder {
        result: Result<BuildOutput>,
    }

    #[async_trait::async_trait]
    impl BuildBackend for StubBuilder {
        async fn build(&self, _repo_path: &Path) -> Result<BuildOutput> {
            match &self.result {
                Ok(out) => Ok(out.clone()),
                Err(e) => Err(anyhow::anyhow!("{}", e)),
            }
        }
    }

    #[tokio::test]
    async fn stub_builder_err_returns_error() {
        let stub: Arc<dyn BuildBackend> = Arc::new(StubBuilder {
            result: Err(anyhow::anyhow!("stub failure")),
        });
        let err = stub.build(Path::new("/tmp")).await.unwrap_err();
        assert!(err.to_string().contains("stub failure"));
    }

    #[tokio::test]
    async fn stub_builder_ok_returns_output() {
        let stub: Arc<dyn BuildBackend> = Arc::new(StubBuilder {
            result: Ok(BuildOutput {
                store_path: PathBuf::from("/nix/store/abc123-test"),
            }),
        });
        let out = stub.build(Path::new("/tmp")).await.unwrap();
        assert_eq!(out.store_path, PathBuf::from("/nix/store/abc123-test"));
    }

    #[test]
    fn default_builder_is_nix_builder() {
        // default_builder() must return a usable Arc<dyn BuildBackend> whose
        // concrete backend is NixBuilder: under restricted mode, a missing
        // flake fails with the restricted-mode message (no auto-gen).
        with_nix_restricted_env(Some("1"), || {
            let rt = tokio::runtime::Builder::new_current_thread()
                .enable_all()
                .build()
                .expect("runtime");
            rt.block_on(async {
                let dir = tempfile::tempdir().expect("tempdir");
                let b = default_builder();
                assert_eq!(Arc::strong_count(&b), 1);
                let err = b
                    .build(dir.path())
                    .await
                    .expect_err("missing flake must fail under restricted mode");
                let msg = err.to_string();
                assert!(
                    msg.contains("RUSSEL_NIX_RESTRICTED"),
                    "default_builder must use NixBuilder restricted gate, got: {msg}"
                );
            });
        });
    }

    /// Serialize mutations of `RUSSEL_NIX_RESTRICTED` and restore even on panic.
    fn with_nix_restricted_env<T>(value: Option<&str>, f: impl FnOnce() -> T) -> T {
        use std::sync::{Mutex, OnceLock};
        static LOCK: OnceLock<Mutex<()>> = OnceLock::new();
        let _lock = LOCK
            .get_or_init(|| Mutex::new(()))
            .lock()
            .unwrap_or_else(|poisoned| poisoned.into_inner());

        struct EnvRestore(Option<std::ffi::OsString>);
        impl Drop for EnvRestore {
            fn drop(&mut self) {
                // SAFETY: exclusive LOCK held; only test code mutates this var.
                unsafe {
                    match self.0.take() {
                        Some(v) => std::env::set_var("RUSSEL_NIX_RESTRICTED", v),
                        None => std::env::remove_var("RUSSEL_NIX_RESTRICTED"),
                    }
                }
            }
        }

        let prev = std::env::var_os("RUSSEL_NIX_RESTRICTED");
        let _restore = EnvRestore(prev);
        // SAFETY: exclusive lock held for the duration of the mutation + body.
        unsafe {
            match value {
                Some(v) => std::env::set_var("RUSSEL_NIX_RESTRICTED", v),
                None => std::env::remove_var("RUSSEL_NIX_RESTRICTED"),
            }
        }
        f()
    }

    #[test]
    fn nix_restricted_enabled_parses_truthy_values() {
        with_nix_restricted_env(None, || {
            assert!(!nix_restricted_enabled());
        });

        for truthy in ["1", "true", "TRUE", "yes", "Yes", " 1 "] {
            with_nix_restricted_env(Some(truthy), || {
                assert!(nix_restricted_enabled(), "expected truthy for {truthy:?}");
            });
        }
        for falsy in ["0", "false", "no", "", "maybe"] {
            with_nix_restricted_env(Some(falsy), || {
                assert!(!nix_restricted_enabled(), "expected falsy for {falsy:?}");
            });
        }
    }

    #[test]
    fn restricted_nix_build_args_force_sandbox() {
        let args = restricted_nix_build_args();
        assert!(
            args.windows(3)
                .any(|w| w == ["--option", "sandbox", "true"])
        );
        assert!(
            args.windows(3)
                .any(|w| w == ["--option", "sandbox-fallback", "false"])
        );
    }

    #[test]
    fn ensure_flake_refuses_autogen_when_restricted() {
        with_nix_restricted_env(Some("1"), || {
            // Hold the env lock for the full async body so parallel tests
            // cannot race RUSSEL_NIX_RESTRICTED.
            let rt = tokio::runtime::Builder::new_current_thread()
                .enable_all()
                .build()
                .expect("runtime");
            rt.block_on(async {
                let dir = tempfile::tempdir().expect("tempdir");
                let builder = NixBuilder;
                let err = builder
                    .ensure_flake_exists(dir.path())
                    .await
                    .expect_err("must refuse missing flake under restricted mode");
                let msg = err.to_string();
                assert!(
                    msg.contains("RUSSEL_NIX_RESTRICTED"),
                    "unexpected error: {msg}"
                );
                assert!(!dir.path().join("flake.nix").exists());

                // Committed regular flake is accepted (do not regenerate).
                std::fs::write(dir.path().join("flake.nix"), "{}\n").unwrap();
                let generated = builder
                    .ensure_flake_exists(dir.path())
                    .await
                    .expect("existing flake allowed");
                assert!(!generated);

                // Leftover auto-generated marker is refused.
                std::fs::write(
                    dir.path().join("flake.nix"),
                    format!("{}{{}}\n", NixBuilder::GENERATED_MARKER),
                )
                .unwrap();
                let err = builder
                    .ensure_flake_exists(dir.path())
                    .await
                    .expect_err("must refuse auto-generated flake");
                assert!(
                    err.to_string().contains("auto-generated"),
                    "unexpected error: {err}"
                );

                // Symlink is refused.
                #[cfg(unix)]
                {
                    let target = dir.path().join("real-flake.nix");
                    std::fs::write(&target, "{}\n").unwrap();
                    let _ = std::fs::remove_file(dir.path().join("flake.nix"));
                    std::os::unix::fs::symlink(&target, dir.path().join("flake.nix")).unwrap();
                    let err = builder
                        .ensure_flake_exists(dir.path())
                        .await
                        .expect_err("must refuse symlink flake.nix");
                    assert!(
                        err.to_string().contains("regular file"),
                        "unexpected error: {err}"
                    );
                }
            });
        });
    }
}
