use std::io::Write;
use std::path::{Path, PathBuf};
use std::sync::{Arc, OnceLock};

use anyhow::Result;
use tokio::process::Command;

#[derive(Debug, Clone)]
pub struct BuildOutput {
    pub store_path: PathBuf,
}

static CURRENT_SYSTEM: OnceLock<String> = OnceLock::new();
/// Detect and cache the Nix system triple (e.g. `x86_64-linux`).
/// Called once at startup; must complete before any build/deploy.
pub async fn init_current_system() -> Result<()> {
    let output = Command::new("nix")
        .args([
            "eval",
            "--impure",
            "--raw",
            "--expr",
            "builtins.currentSystem",
        ])
        .output()
        .await?;

    if !output.status.success() {
        anyhow::bail!(
            "failed to detect Nix system: {}",
            String::from_utf8_lossy(&output.stderr).trim()
        );
    }

    let stdout = String::from_utf8(output.stdout)
        .map_err(|e| anyhow::anyhow!("nix eval output is not valid UTF-8: {e}"))?;
    let sys = stdout.trim().to_string();
    if sys.is_empty() {
        anyhow::bail!("nix eval builtins.currentSystem returned empty output");
    }
    // Reject values that don't look like a Nix system triple (e.g. x86_64-linux).
    if !sys
        .chars()
        .all(|c| c.is_ascii_alphanumeric() || c == '_' || c == '-')
        || !sys.contains('-')
    {
        anyhow::bail!(
            "nix eval returned unrecognized system triple format: {sys:?} \
             (expected e.g. x86_64-linux or aarch64-darwin)"
        );
    }
    let _ = CURRENT_SYSTEM.set(sys);
    Ok(())
}

/// Return the cached system triple; panics if `init_current_system` was not called.
#[inline]
pub fn current_system() -> &'static str {
    CURRENT_SYSTEM
        .get()
        .unwrap_or_else(|| {
            panic!(
                "current_system() called before init_current_system() — \
                 call init_current_system() at startup"
            )
        })
        .as_str()
}

/// Pluggable build backend — mirrors the `Ingress` trait pattern.
///
/// DeployPipeline holds an `Arc<dyn BuildBackend>` so future providers
/// (container-first, remote build farm, Bazel) can be swapped in without
/// touching the deploy orchestration.
#[async_trait::async_trait]
pub trait BuildBackend: Send + Sync {
    async fn build(&self, repo_path: &Path) -> Result<BuildOutput>;
}

/// Default build backend backed by `nix build` on the local machine.
#[derive(Debug, Default)]
pub struct NixBuilder;

impl NixBuilder {
    /// Marker inserted as the first line of auto-generated flake.nix files.
    /// Used to identify and optionally clean up generated flakes after a
    /// successful build, leaving the checkout clean.
    const GENERATED_MARKER: &'static str = "# Auto-generated by Russel — do not edit manually.\n";

    pub async fn ensure_flake_exists(&self, repo_path: &Path) -> Result<bool> {
        let flake_path = repo_path.join("flake.nix");
        // Use create_new for atomic check-and-create (fail if exists, no TOCTOU).
        let mut opts = std::fs::OpenOptions::new();
        opts.write(true).create_new(true);
        #[cfg(unix)]
        {
            use std::os::unix::fs::OpenOptionsExt;
            opts.custom_flags(libc::O_NOFOLLOW | libc::O_CLOEXEC);
        }
        let mut file = match opts.open(&flake_path) {
            Ok(f) => f,
            Err(e) if e.kind() == std::io::ErrorKind::AlreadyExists => return Ok(false),
            Err(e) => return Err(e.into()),
        };

        let system = current_system();
        tracing::info!(system = %system, "No flake.nix found. Auto-detecting project type to generate a default flake.");

        let flake_body = if repo_path.join("Cargo.toml").exists() {
            tracing::info!("Detected Rust project.");
            format!(
                r#"{{
  description = "Auto-generated Rust flake by Russel";
  inputs.nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
  outputs = {{ self, nixpkgs }}:
    let
      pkgs = nixpkgs.legacyPackages.{system};
    in {{
      packages.{system}.default = pkgs.rustPlatform.buildRustPackage {{
        pname = "app";
        version = "0.1.0";
        src = ./.;
        cargoLock = {{
          lockFile = ./Cargo.lock;
        }};
      }};
    }};
}}"#,
                system = system
            )
        } else if repo_path.join("go.mod").exists() {
            tracing::info!("Detected Go project.");
            format!(
                r#"{{
  description = "Auto-generated Go flake by Russel";
  inputs.nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
  outputs = {{ self, nixpkgs }}:
    let
      pkgs = nixpkgs.legacyPackages.{system};
    in {{
      packages.{system}.default = pkgs.buildGoModule {{
        pname = "app";
        version = "0.1.0";
        src = ./.;
        vendorHash = null;
      }};
    }};
}}"#,
                system = system
            )
        } else {
            tracing::info!("Defaulting to static web server flake.");
            format!(
                r#"{{
  description = "Auto-generated Static site flake by Russel";
  inputs.nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
  outputs = {{ self, nixpkgs }}:
    let
      pkgs = nixpkgs.legacyPackages.{system};
    in {{
      packages.{system}.default = pkgs.writeShellScriptBin "app" ''
        cd ${{./.}}
        exec ${{pkgs.python3}}/bin/python3 -m http.server "$PORT"
      '';
    }};
}}"#,
                system = system
            )
        };

        let flake_content = format!("{}{}", Self::GENERATED_MARKER, flake_body);
        file.write_all(flake_content.as_bytes())?;
        tracing::info!("Successfully generated default flake.nix");
        Ok(true)
    }

    /// Build using `nix build`; the inherent entry point for callers that
    /// hold a concrete `NixBuilder` (delegates to `build_package`).
    #[allow(dead_code)]
    pub async fn build(&self, repo_path: &Path) -> Result<BuildOutput> {
        self.build_package(repo_path).await
    }

    /// Shared implementation: generates a flake if missing, runs `nix build`,
    /// and cleans up the auto-generated flake on success.
    async fn build_package(&self, repo_path: &Path) -> Result<BuildOutput> {
        let generated = self.ensure_flake_exists(repo_path).await?;

        let build_result = self.build_inner(repo_path).await;

        // On success, remove the auto-generated flake to leave the checkout clean.
        // Only remove it if the marker is present (defense in depth: never delete
        // a flake.nix the user wrote themselves).
        if build_result.is_ok() && generated {
            let flake_path = repo_path.join("flake.nix");
            if let Ok(content) = std::fs::read_to_string(&flake_path)
                && content.starts_with(Self::GENERATED_MARKER)
            {
                if let Err(e) = std::fs::remove_file(&flake_path) {
                    tracing::warn!(
                        path = %flake_path.display(),
                        error = %e,
                        "failed to remove auto-generated flake.nix after successful build"
                    );
                } else {
                    tracing::info!("removed auto-generated flake.nix after successful build");
                }
            }
        } else if build_result.is_err() && generated {
            let flake_path = repo_path.join("flake.nix");
            tracing::warn!(
                path = %flake_path.display(),
                "build failed; leaving auto-generated flake.nix for inspection"
            );
        }

        build_result
    }

    async fn build_inner(&self, repo_path: &Path) -> Result<BuildOutput> {
        let system = current_system();
        let flake_ref = format!("path:{}#packages.{}.default", repo_path.display(), system);
        let mut output = Command::new("nix")
            .arg("build")
            .arg(&flake_ref)
            .arg("--no-link")
            .arg("--print-out-paths")
            .stderr(std::process::Stdio::inherit())
            .output()
            .await?;

        if !output.status.success() {
            let fallback_ref = format!("path:{}#defaultPackage.{}", repo_path.display(), system);
            tracing::info!(system = %system, "packages.{}.default failed, trying defaultPackage", system);
            output = Command::new("nix")
                .arg("build")
                .arg(&fallback_ref)
                .arg("--no-link")
                .arg("--print-out-paths")
                .stderr(std::process::Stdio::piped())
                .output()
                .await?;

            if !output.status.success() {
                anyhow::bail!(
                    "nix build failed for both {} and {}:\n{}",
                    flake_ref,
                    fallback_ref,
                    String::from_utf8_lossy(&output.stderr).trim()
                );
            }
        }

        let store_path_raw = String::from_utf8_lossy(&output.stdout)
            .lines()
            .next()
            .unwrap_or_default()
            .trim()
            .to_string();

        if store_path_raw.is_empty() {
            anyhow::bail!("nix build produced an empty store path");
        }
        if !store_path_raw.starts_with("/nix/store/") {
            anyhow::bail!(
                "nix build returned unexpected path '{}' (expected /nix/store/ prefix)",
                store_path_raw
            );
        }
        let store_path: PathBuf = store_path_raw.into();

        Ok(BuildOutput { store_path })
    }
}

#[async_trait::async_trait]
impl BuildBackend for NixBuilder {
    async fn build(&self, repo_path: &Path) -> Result<BuildOutput> {
        self.build_package(repo_path).await
    }
}

/// Return the default build backend (local `nix build`).
pub fn default_builder() -> Arc<dyn BuildBackend> {
    Arc::new(NixBuilder)
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used)]
mod tests {
    use super::*;

    struct StubBuilder {
        result: Result<BuildOutput>,
    }

    #[async_trait::async_trait]
    impl BuildBackend for StubBuilder {
        async fn build(&self, _repo_path: &Path) -> Result<BuildOutput> {
            match &self.result {
                Ok(out) => Ok(out.clone()),
                Err(e) => Err(anyhow::anyhow!("{}", e)),
            }
        }
    }

    #[tokio::test]
    async fn stub_builder_err_returns_error() {
        let stub: Arc<dyn BuildBackend> = Arc::new(StubBuilder {
            result: Err(anyhow::anyhow!("stub failure")),
        });
        let err = stub.build(Path::new("/tmp")).await.unwrap_err();
        assert!(err.to_string().contains("stub failure"));
    }

    #[tokio::test]
    async fn stub_builder_ok_returns_output() {
        let stub: Arc<dyn BuildBackend> = Arc::new(StubBuilder {
            result: Ok(BuildOutput {
                store_path: PathBuf::from("/nix/store/abc123-test"),
            }),
        });
        let out = stub.build(Path::new("/tmp")).await.unwrap();
        assert_eq!(out.store_path, PathBuf::from("/nix/store/abc123-test"));
    }

    #[test]
    fn default_builder_is_nix_builder() {
        // default_builder() must return an Arc that can be used as a trait object.
        let b = default_builder();
        let _: &dyn BuildBackend = b.as_ref();
    }
}
