{
  description = "basic-http — Russel example app";

  # This flake is for local development only (nix develop, nix build).
  # MicroVM configuration is generated by russel-ctrl from Russelfile.toml
  # and lives in /var/lib/russel/<vm-id>/flake.nix — not here.
  inputs.nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";

  outputs = { self, nixpkgs }:
    let
      system = "x86_64-linux";
      pkgs   = import nixpkgs { inherit system; };

      app = pkgs.buildGoModule {
        pname       = "api";
        version     = "0.1.0";
        src         = ./.;
        vendorHash  = null;
      };
    in {
      # Used by russel-ctrl: imported as app-src.packages.default in deploy.nix
      packages.${system}.default = app;

      # Local dev shell — unaffected by russel deployments
      devShells.${system}.default = pkgs.mkShell {
        buildInputs = [ pkgs.go pkgs.gopls pkgs.gotools ];
      };
    };
}
